export type WordPair = {
  normal: string;
  impostor: string;
};

export const WORD_PAIRS: WordPair[] = [
  { normal: 'Plage', impostor: 'Mer' },
  { normal: 'Forêt', impostor: 'Jungle' },
  { normal: 'Chat', impostor: 'Tigre' },
  { normal: 'Chien', impostor: 'Loup' },
  { normal: 'Voiture', impostor: 'Camion' },
  { normal: 'Avion', impostor: 'Hélicoptère' },
  { normal: 'Train', impostor: 'Métro' },
  { normal: 'Bateau', impostor: 'Sous-marin' },
  { normal: 'Maison', impostor: 'Château' },
  { normal: 'Appartement', impostor: 'Hôtel' },

  { normal: 'Pizza', impostor: 'Tarte' },
  { normal: 'Burger', impostor: 'Sandwich' },
  { normal: 'Frites', impostor: 'Chips' },
  { normal: 'Pomme', impostor: 'Poire' },
  { normal: 'Banane', impostor: 'Ananas' },
  { normal: 'Fraise', impostor: 'Framboise' },
  { normal: 'Orange', impostor: 'Citron' },
  { normal: 'Pastèque', impostor: 'Melon' },
  { normal: 'Carotte', impostor: 'Radis' },
  { normal: 'Tomate', impostor: 'Poivron' },

  { normal: 'Café', impostor: 'Thé' },
  { normal: 'Bière', impostor: 'Soda' },
  { normal: 'Eau', impostor: 'Limonade' },
  { normal: 'Glace', impostor: 'Yaourt' },
  { normal: 'Chocolat', impostor: 'Caramel' },
  { normal: 'Croissant', impostor: 'Pain au chocolat' },
  { normal: 'Baguette', impostor: 'Pain' },
  { normal: 'Crêpe', impostor: 'Gaufre' },
  { normal: 'Bonbon', impostor: 'Sucette' },
  { normal: 'Popcorn', impostor: 'Céréales' },

  { normal: 'Soleil', impostor: 'Lune' },
  { normal: 'Étoile', impostor: 'Planète' },
  { normal: 'Nuage', impostor: 'Brouillard' },
  { normal: 'Pluie', impostor: 'Neige' },
  { normal: 'Orage', impostor: 'Tempête' },
  { normal: 'Volcan', impostor: 'Montagne' },
  { normal: 'Rivière', impostor: 'Lac' },
  { normal: 'Cascade', impostor: 'Fontaine' },
  { normal: 'Désert', impostor: 'Savane' },
  { normal: 'Île', impostor: 'Continent' },

  { normal: 'Téléphone', impostor: 'Tablette' },
  { normal: 'Ordinateur', impostor: 'Télévision' },
  { normal: 'Clavier', impostor: 'Piano' },
  { normal: 'Souris', impostor: 'Manette' },
  { normal: 'Casque', impostor: 'Écouteurs' },
  { normal: 'Caméra', impostor: 'Appareil photo' },
  { normal: 'Microphone', impostor: 'Haut-parleur' },
  { normal: 'Montre', impostor: 'Réveil' },
  { normal: 'Ampoule', impostor: 'Bougie' },
  { normal: 'Robot', impostor: 'Humain' },

  { normal: 'Football', impostor: 'Rugby' },
  { normal: 'Basket', impostor: 'Handball' },
  { normal: 'Tennis', impostor: 'Badminton' },
  { normal: 'Boxe', impostor: 'Karaté' },
  { normal: 'Ski', impostor: 'Snowboard' },
  { normal: 'Vélo', impostor: 'Trottinette' },
  { normal: 'Piscine', impostor: 'Mer' },
  { normal: 'Stade', impostor: 'Gymnase' },
  { normal: 'Ballon', impostor: 'Balle' },
  { normal: 'Médaille', impostor: 'Trophée' },

  { normal: 'Épée', impostor: 'Sabre' },
  { normal: 'Arc', impostor: 'Arbalète' },
  { normal: 'Bouclier', impostor: 'Armure' },
  { normal: 'Dragon', impostor: 'Dinosaure' },
  { normal: 'Fantôme', impostor: 'Zombie' },
  { normal: 'Sorcière', impostor: 'Magicien' },
  { normal: 'Vampire', impostor: 'Démon' },
  { normal: 'Chevalier', impostor: 'Samouraï' },
  { normal: 'Pirate', impostor: 'Marin' },
  { normal: 'Trésor', impostor: 'Coffre' },

  { normal: 'Lit', impostor: 'Canapé' },
  { normal: 'Chaise', impostor: 'Tabouret' },
  { normal: 'Table', impostor: 'Bureau' },
  { normal: 'Four', impostor: 'Micro-ondes' },
  { normal: 'Frigo', impostor: 'Congélateur' },
  { normal: 'Douche', impostor: 'Baignoire' },
  { normal: 'Fenêtre', impostor: 'Porte' },
  { normal: 'Escalier', impostor: 'Échelle' },
  { normal: 'Lampe', impostor: 'Lampadaire' },
  { normal: 'Horloge', impostor: 'Montre' },

  { normal: 'Lion', impostor: 'Tigre' },
  { normal: 'Éléphant', impostor: 'Rhinocéros' },
  { normal: 'Girafe', impostor: 'Zèbre' },
  { normal: 'Requin', impostor: 'Dauphin' },
  { normal: 'Baleine', impostor: 'Orque' },
  { normal: 'Pingouin', impostor: 'Canard' },
  { normal: 'Aigle', impostor: 'Faucon' },
  { normal: 'Papillon', impostor: 'Abeille' },
  { normal: 'Araignée', impostor: 'Scorpion' },
  { normal: 'Serpent', impostor: 'Lézard' },

  { normal: 'Couronne', impostor: 'Chapeau' },
  { normal: 'Lunettes', impostor: 'Masque' },
  { normal: 'Chaussure', impostor: 'Chaussette' },
  { normal: 'Pantalon', impostor: 'Short' },
  { normal: 'Chemise', impostor: 'T-shirt' },
  { normal: 'Sac', impostor: 'Valise' },
  { normal: 'Parapluie', impostor: 'Parasol' },
  { normal: 'Clé', impostor: 'Cadenas' },
  { normal: 'Livre', impostor: 'Cahier' },
  { normal: 'Crayon', impostor: 'Pinceau' },
];